SELECT DISTINCT TERMEKEK.NEV
FROM TERMEKEK
INNER 
JOIN VASAROL 
ON TERMEKEK.KOD = VASAROL.TERMEK_KOD
INNER 
JOIN VASARLASOK 
ON VASARLASOK.ID = VASAROL.VASARLAS_ID
WHERE VASARLASOK.VASARLO_EMAIL IN 
(
SELECT VASARLASOK.VASARLO_EMAIL FROM VASAROL
INNER 
JOIN VASARLASOK 
ON VASAROL.VASARLAS_ID = VASARLASOK.ID 
WHERE VASAROL.TERMEK_KOD = 2 )
AND TERMEKEK.KOD != 2;
